spring.application.name=customer-service

spring.datasource.url=jdbc:h2:mem:customer-db
spring.h2.console.enabled=true
server.port=8081
spring.cloud.config.enabled=false
spring.cloud.discovery.enabled=false

spring.data.rest.base-path=/api