spring.application.name=billing-service

server.port=8083
spring.config.import=optional:configserver:http://localhost:9999

# Spring Cloud Stream Kafka consumer binding for customer events
# spring.cloud.stream.bindings.customerConsumer-in-0.destination=customerTopic
# spring.cloud.stream.bindings.customerConsumer-in-0.group=billing-service-group
# spring.cloud.stream.bindings.customerConsumer-in-0.contentType=application/json
# spring.cloud.stream.kafka.binder.brokers=localhost:9092